### ISSUE TITLE
randomarticle.php should enforce namespace = 0

### ISSUE THREAD

**Issue by Huji** [erwin85/erwin85#2]
Currently, it returns a random **page** (and not a random **article**).

Either a dropdown should be added to allow for specifying a namespace, or it should simply enforce namespace = 0 in its query. Since getting a random page from a category is now as easy as Special:RandomInCategory/CATNAME I think the latter (i.e. enforcing the namespace = 0) is the better solution here.

**Comment by nemobis** [comment]
Huji Lee, 15/08/2018 02:37:
> Currently, it returns a random *page* (and not a random *article*).

And why is that a problem? Users are often insterested in pages outside 
namespace 0, for instance I see a request that was most likely for files:
/erwin85/randomarticle.php?lang=&family=commons&categories=Vexillology&subcats=1&d=2

By the way, we track issues on Phabricator: 
https://phabricator.wikimedia.org/project/profile/775/
Should we close the issue reporting here?

**Comment by Huji** [comment]
Lets close it here. I will recreate and elaborate on Phab.

**Comment by nemobis** [comment]
Huji Lee, 15/08/2018 15:56:
> Lets close it here. I will recreate and elaborate on Phab.

Ok, thanks. (This issue will now become inaccessible as I close bug 
reporting, but it's actually still stored.)
